# Generated by Django 3.0.14 on 2021-11-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjarticles',
            name='important',
            field=models.BooleanField(default=0, verbose_name='Czy ważny'),
        ),
    ]
