# Generated by Django 3.0.14 on 2021-11-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0002_pjarticles_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='PJComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Użytkownik')),
                ('comment', models.TextField(verbose_name='Komentarz')),
                ('pub_data', models.DateTimeField(auto_now_add=True, verbose_name='Data Publikacji')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pjarticles.PJArticles')),
            ],
        ),
    ]
