# Generated by Django 3.0.14 on 2021-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0003_pjcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjarticles',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Obrazek'),
        ),
    ]
