# Generated by Django 3.2.9 on 2022-01-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0005_remove_pjarticles_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pjarticles',
            name='important',
        ),
    ]
