# Generated by Django 3.2.9 on 2022-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0006_remove_pjarticles_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjarticles',
            name='important',
            field=models.BooleanField(default=0, verbose_name='Czy ważny'),
        ),
    ]
