# Generated by Django 3.0.14 on 2022-01-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0007_pjarticles_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjarticles',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='Obrazek'),
        ),
    ]
