# Generated by Django 4.0.1 on 2022-01-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjarticles', '0009_alter_pjarticles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjarticles',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Opublikowany?'),
        ),
    ]
